export default Reflect;
export var apply = Reflect.apply;
export var construct = Reflect.construct;
export var defineProperty = Reflect.defineProperty;
export var deleteProperty = Reflect.deleteProperty;
export var enumerate = Reflect.enumerate;
export var get = Reflect.get;
export var getOwnPropertyDescriptor = Reflect.getOwnPropertyDescriptor;
export var has = Reflect.has;
export var isExtensible = Reflect.isExtensible;
export var ownKeys = Reflect.ownKeys;
export var preventExtensions = Reflect.preventExtensions;
export var set = Reflect.set;
export var setPrototypeOf = Reflect.setPrototypeOf;
export var set = Reflect.set;
